services:
  pokedex-api:
    build: ./pokedex_api
    container_name: pokedex_api
    ports: 
      - 3030:3030
    volumes:
      - ./pokedex_api:/code/pokedex_api
    tty: true
  
  pokedex-web:
    image: node:22-alpine3.19
    container_name: pokedex_web_app
    ports:
      - 5173:5173
    volumes:
      - ./pokedex_web_app:/code/pokedex_web_app
    tty: true
    
