services:
  pokedex-api:
    build: ./pokedex_api
    container_name: pokedex_api
    ports: 
      - 3030:3030
    volumes:
      - ./pokedex_api:/code/pokedex_api
    command: ["cargo", "run"] 
  
  pokedex-web:
    build: ./pokedex_web_app
    container_name: pokedex_web_app
    ports:
      - 5173:5173
    volumes:
      - ./pokedex_web_app:/code/pokedex_web_app
    command: /bin/sh -c "npm install && npm run dev"
    
