FROM node:22-alpine3.19

# Set the working directory
WORKDIR /code/pokedex_web_app

# Copy the current directory contents into the container at /code/pokedex_web_app
COPY . /code/pokedex_web_app

# Install the dependencies
RUN npm install